/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedManagementRouteImport } from './routes/_authenticated/management'
import { Route as AuthenticatedAiReportsRouteImport } from './routes/_authenticated/ai-reports'
import { Route as AuthenticatedAccessControlRouteImport } from './routes/_authenticated/access-control'
import { Route as _authVerificationRouteImport } from './routes/__auth/verification'
import { Route as _authSigninRouteImport } from './routes/__auth/signin'
import { Route as _authResetPasswordRouteImport } from './routes/__auth/reset-password'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'

const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagementRoute = AuthenticatedManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiReportsRoute = AuthenticatedAiReportsRouteImport.update({
  id: '/ai-reports',
  path: '/ai-reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccessControlRoute =
  AuthenticatedAccessControlRouteImport.update({
    id: '/access-control',
    path: '/access-control',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const _authVerificationRoute = _authVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authSigninRoute = _authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authResetPasswordRoute = _authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => _authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/access-control': typeof AuthenticatedAccessControlRoute
  '/ai-reports': typeof AuthenticatedAiReportsRoute
  '/management': typeof AuthenticatedManagementRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/access-control': typeof AuthenticatedAccessControlRoute
  '/ai-reports': typeof AuthenticatedAiReportsRoute
  '/management': typeof AuthenticatedManagementRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/reset-password': typeof _authResetPasswordRoute
  '/__auth/signin': typeof _authSigninRoute
  '/__auth/verification': typeof _authVerificationRoute
  '/_authenticated/access-control': typeof AuthenticatedAccessControlRoute
  '/_authenticated/ai-reports': typeof AuthenticatedAiReportsRoute
  '/_authenticated/management': typeof AuthenticatedManagementRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/access-control'
    | '/ai-reports'
    | '/management'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/access-control'
    | '/ai-reports'
    | '/management'
    | '/settings'
  id:
    | '__root__'
    | '/__auth'
    | '/_authenticated'
    | '/accept-invite'
    | '/__auth/forgot-password'
    | '/__auth/reset-password'
    | '/__auth/signin'
    | '/__auth/verification'
    | '/_authenticated/access-control'
    | '/_authenticated/ai-reports'
    | '/_authenticated/management'
    | '/_authenticated/settings'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management': {
      id: '/_authenticated/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AuthenticatedManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-reports': {
      id: '/_authenticated/ai-reports'
      path: '/ai-reports'
      fullPath: '/ai-reports'
      preLoaderRoute: typeof AuthenticatedAiReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access-control': {
      id: '/_authenticated/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AuthenticatedAccessControlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/__auth/verification': {
      id: '/__auth/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof _authVerificationRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/signin': {
      id: '/__auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof _authSigninRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/reset-password': {
      id: '/__auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof _authResetPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authResetPasswordRoute: typeof _authResetPasswordRoute
  _authSigninRoute: typeof _authSigninRoute
  _authVerificationRoute: typeof _authVerificationRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authResetPasswordRoute: _authResetPasswordRoute,
  _authSigninRoute: _authSigninRoute,
  _authVerificationRoute: _authVerificationRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessControlRoute: typeof AuthenticatedAccessControlRoute
  AuthenticatedAiReportsRoute: typeof AuthenticatedAiReportsRoute
  AuthenticatedManagementRoute: typeof AuthenticatedManagementRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessControlRoute: AuthenticatedAccessControlRoute,
  AuthenticatedAiReportsRoute: AuthenticatedAiReportsRoute,
  AuthenticatedManagementRoute: AuthenticatedManagementRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
