/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _mainRouteRouteImport } from './routes/__main/route'
import { Route as _authRouteRouteImport } from './routes/__auth/route'
import { Route as _mainIndexRouteImport } from './routes/__main/index'
import { Route as _mainSettingsRouteImport } from './routes/__main/settings'
import { Route as _mainManagementRouteImport } from './routes/__main/management'
import { Route as _mainAiReportsRouteImport } from './routes/__main/ai-reports'
import { Route as _mainAccessControlRouteImport } from './routes/__main/access-control'
import { Route as _authVerificationRouteImport } from './routes/__auth/verification'
import { Route as _authSigninRouteImport } from './routes/__auth/signin'
import { Route as _authResetPasswordRouteImport } from './routes/__auth/reset-password'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'

const _mainRouteRoute = _mainRouteRouteImport.update({
  id: '/__main',
  getParentRoute: () => rootRouteImport,
} as any)
const _authRouteRoute = _authRouteRouteImport.update({
  id: '/__auth',
  getParentRoute: () => rootRouteImport,
} as any)
const _mainIndexRoute = _mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainSettingsRoute = _mainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainManagementRoute = _mainManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainAiReportsRoute = _mainAiReportsRouteImport.update({
  id: '/ai-reports',
  path: '/ai-reports',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _mainAccessControlRoute = _mainAccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => _mainRouteRoute,
} as any)
const _authVerificationRoute = _authVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authSigninRoute = _authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authResetPasswordRoute = _authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => _authRouteRoute,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => _authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _mainIndexRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/access-control': typeof _mainAccessControlRoute
  '/ai-reports': typeof _mainAiReportsRoute
  '/management': typeof _mainManagementRoute
  '/settings': typeof _mainSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof _mainIndexRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/reset-password': typeof _authResetPasswordRoute
  '/signin': typeof _authSigninRoute
  '/verification': typeof _authVerificationRoute
  '/access-control': typeof _mainAccessControlRoute
  '/ai-reports': typeof _mainAiReportsRoute
  '/management': typeof _mainManagementRoute
  '/settings': typeof _mainSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__auth': typeof _authRouteRouteWithChildren
  '/__main': typeof _mainRouteRouteWithChildren
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/reset-password': typeof _authResetPasswordRoute
  '/__auth/signin': typeof _authSigninRoute
  '/__auth/verification': typeof _authVerificationRoute
  '/__main/access-control': typeof _mainAccessControlRoute
  '/__main/ai-reports': typeof _mainAiReportsRoute
  '/__main/management': typeof _mainManagementRoute
  '/__main/settings': typeof _mainSettingsRoute
  '/__main/': typeof _mainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/access-control'
    | '/ai-reports'
    | '/management'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/verification'
    | '/access-control'
    | '/ai-reports'
    | '/management'
    | '/settings'
  id:
    | '__root__'
    | '/__auth'
    | '/__main'
    | '/__auth/forgot-password'
    | '/__auth/reset-password'
    | '/__auth/signin'
    | '/__auth/verification'
    | '/__main/access-control'
    | '/__main/ai-reports'
    | '/__main/management'
    | '/__main/settings'
    | '/__main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authRouteRoute: typeof _authRouteRouteWithChildren
  _mainRouteRoute: typeof _mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__main': {
      id: '/__main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth': {
      id: '/__auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__main/': {
      id: '/__main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _mainIndexRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/settings': {
      id: '/__main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof _mainSettingsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/management': {
      id: '/__main/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof _mainManagementRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/ai-reports': {
      id: '/__main/ai-reports'
      path: '/ai-reports'
      fullPath: '/ai-reports'
      preLoaderRoute: typeof _mainAiReportsRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__main/access-control': {
      id: '/__main/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof _mainAccessControlRouteImport
      parentRoute: typeof _mainRouteRoute
    }
    '/__auth/verification': {
      id: '/__auth/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof _authVerificationRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/signin': {
      id: '/__auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof _authSigninRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/reset-password': {
      id: '/__auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof _authResetPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof _authRouteRoute
    }
  }
}

interface _authRouteRouteChildren {
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authResetPasswordRoute: typeof _authResetPasswordRoute
  _authSigninRoute: typeof _authSigninRoute
  _authVerificationRoute: typeof _authVerificationRoute
}

const _authRouteRouteChildren: _authRouteRouteChildren = {
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authResetPasswordRoute: _authResetPasswordRoute,
  _authSigninRoute: _authSigninRoute,
  _authVerificationRoute: _authVerificationRoute,
}

const _authRouteRouteWithChildren = _authRouteRoute._addFileChildren(
  _authRouteRouteChildren,
)

interface _mainRouteRouteChildren {
  _mainAccessControlRoute: typeof _mainAccessControlRoute
  _mainAiReportsRoute: typeof _mainAiReportsRoute
  _mainManagementRoute: typeof _mainManagementRoute
  _mainSettingsRoute: typeof _mainSettingsRoute
  _mainIndexRoute: typeof _mainIndexRoute
}

const _mainRouteRouteChildren: _mainRouteRouteChildren = {
  _mainAccessControlRoute: _mainAccessControlRoute,
  _mainAiReportsRoute: _mainAiReportsRoute,
  _mainManagementRoute: _mainManagementRoute,
  _mainSettingsRoute: _mainSettingsRoute,
  _mainIndexRoute: _mainIndexRoute,
}

const _mainRouteRouteWithChildren = _mainRouteRoute._addFileChildren(
  _mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authRouteRoute: _authRouteRouteWithChildren,
  _mainRouteRoute: _mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
